language: node_js
node_js:
- '6'
env:
- NODE_ENV=production
- CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_install:
  - nvm --version
  - node --version
  - npm --version
  - gcc --version
  - g++ --version
  - npm install -g yarn --cache-min 999999999
install:
- yarn
before_script:
- npm run lint
- sleep 15
script:
- npm run build-dev
- npm run build
- npm test
sudo: required
notifications:
  email:
  - michael.l.dangelo@gmail.com
git:
  depth: 10
cache:
  yarn: true
  directories:
  - node_modules
addons:
    code_climate:
        repo_token: 321ece2c9941bf30bb07f0555343ad772bdbbc6235c866478afc7af46558a8b4
